/*
 * This file was generated by the Gradle 'init' task.
 *
 * The settings file is used to specify which projects to include in your build.
 *
 * Detailed information about configuring a multi-project build in Gradle can be found
 * in the user guide at https://docs.gradle.org/4.5/userguide/multi_project_builds.html
 */

rootProject.name = "4sijte"

pluginManagement {
    repositories {
        gradlePluginPortal()
        jcenter()
        mavenLocal()
        jcenter()
        mavenCentral()
    }
    resolutionStrategy {
        eachPlugin {
            if (requested.id.id == "jooby") {
                useModule("org.jooby:jooby-gradle-plugin:${requested.version}")
            }
        }
    }
}
