package fsijte

import fsijte.controllers.LibraryApi
import fsijte.util.Constants
import org.jooby.*
import org.jooby.json.Jackson

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
class App: Kooby({

    assets("/", Constants.DEFAULT_WEB_PAGE)
    assets("/login",Constants.DEFAULT_WEB_PAGE)
    assets("/favicon.png")
    assets("/css/**")
    assets("/js/**")

    use(Jackson())
    use(LibraryApi::class)

}) {
    companion object {
        @JvmStatic
        fun main(args: Array<String>) {
            run(::App, *args)
        }

    }
}
