package fsijte

import org.jooby.*
/*
 * This Java source file was generated by the Gradle 'init' task.
 */
class App: Kooby({
    get {
        "Hello Jooby"
    }
})

fun main(args: Array<String>) {
    run(::App, *args)
//    @JvmStatic
//    fun main(args:Array<String> ) {
//        println(App.greeting())
//    }
}
