package fsijte

import org.jooby.*

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
class App: Kooby({
    get {
        "Hello Jooby"
    }

}) {
    companion object {
        @JvmStatic
        fun main(args: Array<String>) {
            run(::App, *args)
        }

    }
}
